### ISSUE TITLE
most.unfold does not emit tuple.value that is returned with tuple.done == true

### ISSUE THREAD

**Issue by maciasello** [cujojs/most#100]
Reproducing code (prints only 0 and 1):
```javascript
most.unfold(function(s) {
    return {value: s, seed: s+1, done: s==2};
}, 0)
.forEach(console.log.bind(console));
```

Additional code :) (prints 0, 1, 2 as the last tuple.value goes as forEach's promise resolution value):
```javascript
most.unfold(function(s) {
    return {value: s, seed: s+1, done: s==2};
}, 0)
.forEach(console.log.bind(console))
.then(console.log.bind(console));
```

There is a question if it is a matter of unclear documentation or a bug.

My first approach was that tuple.value returned in last loop (tuple.done == true) will be emitted as last event in the stream. Instead it is attached to the end event (and is a resolution value of the promise returned by forEach - did not check how other consumers handle it). The docs do not mention neither a concept of a value attached to the end event nor what will be resolution value on forEach. So if it is not a bug then these docs should be updated too.

I would go with a PR but some discussion is needed on the approach to take. My gut feeling is that it should be last "normal" event. Even then some hints about forEach's promise resolution value would be valuable, but I'm not sure what is its purpose now.

**Comment by davidchase** [comment]
I would say its not a bug but expected, since the `unfold` will terminate as soon as `2 == 2`, rather than something like `s > 2` where you will get `0,1,2` because `s` will increment once again before terminating since `2 > 2` is false.

**Comment by briancavalier** [comment]
@maciasello Thanks for raising this issue!  As @davidchase says, the current behavior is correct: `unfold` behaves like "up to" rather than "up to and including".  The bug is the fact that the documentation is lacking!

Note that it may be clearer in some cases to use `take` to declaratively limit the `unfold`, rather than worrying about `done`.  IOW, sometimes it's easier to write an infinite computation and use `take`, and sometimes it's easier to write a finite one that limits itself using `done` :)

**Comment by briancavalier** [comment]
@maciasello See #104 :)

**Comment by maciasello** [comment]
@davidchase, @briancavalier, I understand that it behaves like this right now and the code looks like it was expected behaviour (not a sneaky bug). But the question here is more of what is more natural. In my case it was natural that in the last iteration I had last value to be emitted normally and also an information that it is last one. Do you have any hints why current approach is more natural/typical?

What is more I did not find any doc about an end event value (besides the one that was added in #104). If we are to stay with current approach, IMHO, it would be worth documenting that there is such a concept and how particular operations treat it (on producer and consumer sides). Maybe notation should be extended as well. Sorry for the "escalation", it just seems that there is non-trivial feature [nearly - #104] not mentioned at all. I'm ready to submit a PR if you still support the current state of situation.

**Comment by maciasello** [comment]
@briancavalier regarding your suggestion to use `take()` (or rather split the process to creation of infinite stream and then cut it by other means) here is my current implementation (that works with current approach on `unfold()`:
```javascript
most.unfold(function(shouldReportDone) {
  if (shouldReportDone) {
    return {
      done: true
    };
  }
  return getPartialResults().then(function(result) {
    return {
      value: result.results,
      seed: result.final,
      done: false
    };
  });
}, false);
```

My first approach was like this (but - now obviously - it produced wrong results):
```javascript
most.unfold(function() {
  return getPartialResults().then(function(result) {
    return {
      value: result.results,
      seed: null,
      done: result.final
    };
  });
}, null);
```

I suppose I'm overlooking some parts of the API but I can't find a compact way to handle it with infinite stream that is cut afterwards. Could you suggest how you would approach the problem?

**Comment by briancavalier** [comment]
@maciasello Ah, ok, thanks for the examples.

The stream we have here *isn't naturally infinite*.  It *will* end on its own, and `getPartialResults` is the only one who can actually tell us when that has happened.  In that case, using `tuple.done` certainly makes sense.  I think your version that checks `shouldReportDone` is actually a good fit, imho.  You could omit the `done: false` and use a ternary if you want it to be more compact.

In ES6, it can be quite nice:

```js
most.unfold(function(done) {
	return done ? { done: true }
		: getPartialResults().then(result => { value: result.results, seed: result.final });
}, false)
	.observe(x => console.log(x));
```

I'll try to explain our thinking a bit.  [Anamorphic unfolding](http://en.wikipedia.org/wiki/Anamorphism) is a fairly standard thing in the functional programming world, and we've ported the idea here, and also tried to use concepts present in ES6 iterators.  In an ES6 generator for example:

```js
function* countdown(n) {
    while(--n >= 0) yield n;
}
```

That will yield tuples with `value` 9 down to (and including 0), all with `done: false`, and then a final `done: true` tuple.  Adding a return:

```js
function* countdown(n) {
    while(--n >= 0) yield n;
    return n;
}
```

Causes `{done: true, value: -1}` to be the last iteration.  It is distinctly different since it is caused by introducing a different construct, a `return`, rather than a `yield`.  So, that's why the `{done: true, value:...}` is handled differently in most.js.  The "yielded" values (those with `done == false`) are used as events and the "returned" value (the one with `done == true`) is used as the end value, that is the value of the promise returned by `observe` or `forEach`.

I hope that helps explain our thinking.

As for 'take', when you don't know ahead of time how many events you want, `take` can't really help.  However, there are other limiting combinators, like `takeWhile` and `until` (aka `takeUntil`), and it just depends on the situation and what you need to do.

**Comment by maciasello** [comment]
@briancavalier, thanks for the detailed explanation. It looks like the value in keeping it consistent with existing concepts is high and I'm not going to push further :)

I'll try to go through the docs and submit a PR with a notion of end value of the streams.
