### ISSUE TITLE
Enhance docs to clarify end signal value handling in "complex" cases

### ISSUE THREAD

**Issue by maciasello** [cujojs/most#106]
#105 documents end signal value handling in simple cases, but some stream methods behaviour on end signal value is not obvious, so I open the issue for discussion on those.

Open questions:
- does `generate` treat return (not yield) value from generator as end signal value?
- what happens with `stream1` end signal value in `concat`?
- does `map` apply `f` on end signal value?
- does `constant` replace end signal value with the constant?
- does `scan` include end signal value in the computation or emits it unchanged or discards or it can be influenced?
- does `flatMap` emit end signal at all? if so - which or computed in what way?
- same for `concatMap` and `ap`
- does `timestamp` decorate the end signal value the same way as it does normal values?
- is the `tap` handler invoked for end signal value?
- can `filter` filter out the end signal value?
- same for `distinct`, `distinctBy`, `slice`, `take`, `skip`, `takeWhile`, `skipWhile`, `during`
- should `endSignal` stream value in `until` be taken as end signal value for the result stream?
-  how does `reduce` treat the end signal value?
- is it OK that `drain` emits the end signal value in the returned Promise?
- how does `combine` work on end signal values?
- same for `lift`, `sample`, `sampleWith`, `zip`, `join`, `await`, `throttle`, `debounce`, `delay`
- does the stream from `switch` emit end signal value of the current stream?

I will try check by myself when I find a spare minute, but for some there is a need to specify the behaviour upfront to verify if they behave ok.

In addition to that should it be mentioned explicitly that some operations (e.g. `startWith`) do not influence end signal value?

**Comment by maciasello** [comment]
Ok. I have already investigated most of the questions, but need to agree on the wording. My picks in square brackets:
1. Is it fine to use 'end signal value' as the term for end signal value :)? [yes]
1. Should it be explicitely stated that end signal value is `null`? [yes]
1. If so should it be `null` or `void 0` in the docs? [null - but really unsure]
1. Should it be explicitely stated that an operation does not touch end signal value? [yes]
1. If so should it be mentioned for operations that create infinite streams? [no]

For now the changes will be only to the docs. I feel that there is a need to have them unit tested, but will not find time for this shortly. I'll document the current state so if anything does not behave as expected it will be a good point to fix it. Expect the commits soon.

**Comment by briancavalier** [comment]
Hey @maciasello, this is really great.  I'll try to answer some of the questions.  Starting with the 3 most recent:

> Is it fine to use 'end signal value' as the term for end signal value :)?

Yes.

> Should it be explicitely stated that end signal value is null?

`Typically, it will be `undefined`.  We could potentially make a blanket statement that unless otherwise noted, the end signal value will be `undefined`.  That could be shown as `-a--b--|` in stream diagrams, which is a nice visual distinction with your idea of showing `-a--b--|x|` when the end value is something other than undefined.

> If so should it be null or void 0 in the docs? [null - but really unsure]

undefined rather than `null`.

> Should it be explicitely stated that an operation does not touch end signal value? [yes]

Another option would be to make a similar blanket statement: unless specified, an operation will not change the end signal value.

> If so should it be mentioned for operations that create infinite streams? [no]

Right, by definition, an infinite stream has no end value.  No need to specify, though another blanket statement to that effect seems perfectly reasonable.

> For now the changes will be only to the docs. I feel that there is a need to have them unit tested

Great, yes, I agree the docs are a good place to start.

**Comment by briancavalier** [comment]
We decided to deprecate the end value.  It turned out not to be composable in many situations, including common ones like `take`.  The end value is always `undefined` in `@most/core` and will follow suit in most 2.0.

Please feel free to reopen if there's more to discuss or there's an approach to end values that may solve the composability issues.
