### ISSUE TITLE
create is not disposing properly when ended early (via take, takeUntil, etc.)

### ISSUE THREAD

**Issue by nissoh** [cujojs/most#129]
Following my comment on #27
http://requirebin.com/?gist=fcabd52e0c21abfa10bc

**Comment by briancavalier** [comment]
Thanks @nissoh.  I'll let you know what I find today.  I actually think this is a problem with `create` rather than with `until`, but I'll report more after I take a closer look.

**Comment by briancavalier** [comment]
Yep, confirmed.  The issue here is with `create`.  Your requirebin example was extremely helpful, thanks for providing it!

I'll try to explain the issue.  In your example, the count function will recurse forever.  There's no way for `most` to prevent that since the recursion is completely self-contained--the timeout is not being canceled, and the timeout handle (i.e. returned by `setTimeout`) is never captured anywhere.  I'm guessing you intended it to work this way to expose the bug, which it did!

However, `most.create` *should* prevent propagation of events after the `takeUntil` signal.  That is where the problem is.  Currently, `most.create` *isn't* forcibly preventing propagation after end.  I'll push a fix for that to a branch shortly, and hopefully you can verify that it fixes the problem.

**Comment by briancavalier** [comment]
@nissoh Could you try the [fix-create-early-end branch](https://github.com/cujojs/most/tree/fix-create-early-end) and let me know if that fixes the issue for you.  Thanks!

**Comment by nissoh** [comment]
Thank you for a very swift response!
Yes, works exactly as i expected.

I don't think the producer is misbehaving. maybe i should've put some background.
I belive this should fix memory leak and unexpected behaviour in [most-w3msg](https://github.com/cujojs/most-w3msg) and many other patterns of publisher subscribers.

Lets say we use w3msg from socket source. we need a way to ultimately unsubscribe from the producer. once disposed, to prevent memory leak our producer must not have any reference to the subscriber so V8 can garbage collect our current subscriber. 

Background: I'm using most for a single page app

**Comment by briancavalier** [comment]
Cool, glad that fixed the issue for you, and thanks for the additional background info.  I'll put together a bug fix release soon.

> I don't think the producer is misbehaving

Sorry if I didn't explain very well.  What I meant here is that the function passed to `most.create` *should* return a function that stops production of new events.  In the [requirebin example](http://requirebin.com/?gist=fcabd52e0c21abfa10bc), there is this construct:

```js
  function count(int) {
    add(int);
    int++;
    setTimeout(count, 1000, int);
  }
  count(1);
```

`count` is an async recursive function, but the recursion never terminates, and the function passed to `create` doesn't return an function to terminate it.  Thus `count` will run forever (until `int` overflows) and there's nothing anyone can do to stop it :)  So, even though after this fix, `most.create` will prevent the `add(int)` from propagating an event, it *cannot* prevent `count` from recursing forever in the code above.

The requirebin should probably do something like the following to manage the timeouts that it is creating internally (i.e. to which `most.create` has no access):

```js
  var t;
  function count(int) {
    console.log('count running', int);
    add(int);
    int++;
    t = setTimeout(count, 1000, int);
  }
  count(1);
  return function() {
    clearTimeout(t);
  }
```

Does that make sense?

**Comment by nissoh** [comment]
Ahhh.. yes.. that wasn't actually intended but i hope it helped (:
That is very interesting.. thanks for clarifying it to me.

**Comment by briancavalier** [comment]
No problem at all!  And yep, it absolutely did help me debug :D
