### ISSUE TITLE
How to unobserve?

### ISSUE THREAD

**Issue by benawhite** [cujojs/most#142]
All other frp libraries support some way to "unobserve", and they all have slightly different implementations to support it. (offValue, dispose, etc...)
Most does not seem to have any direct way to do this.

What do you suggest to people who want to accomplish this task?

```javascript
//returns function to unobserve
var onValue =  function (stream, f) {
  var x;
  stream.takeWhile(function () { return !x; }).observe(f);
  return function () { x = 1; });
};
```

**Comment by briancavalier** [comment]
Hey @benawhite.  Most.js takes a declarative approach.  Rather than an imperative approach where you write procedural code which will later stop observing a stream by calling a function, in a declarative approach, you declare the various constraints about your graph, and let most.js coordinate it.

For example, instead of imperative thinking: "I'll call this function to stop observing Xs later when Y happens", most encourages declarative thinking: "I want all the Xs until Y happens".

Instead of trying to find a way to reproduce your example without any context, I think it would be better to understand your broader use case, and how it can be modeled declaratively.  Can you provide a bit more context?

**Comment by benawhite** [comment]
I wrote an observable model that supports using a stream for sourcing data... 

```JavaScript
model.fromStream(path, stream);
```
If the model is destroyed, it needs to be able to gracefully detach from the stream. Otherwise an error will be thrown setting a value on the destroyed model.

**Comment by AlexGalays** [comment]
So what is the suggestion? Creating a stream that will produce ONE value when the model gets destroyed and feed that to `until` ? Isn't that a bit too much ceremony?

**Comment by AlexGalays** [comment]
By the way, how do you debug whether your streams were properly disposed and are not creating memory leaks? Do something like an `onDispose` callback help diagnostic these?

**Comment by briancavalier** [comment]
@AlexGalays Want to make sure I understand your question.  Are you asking: how do most.js's core developers debug most.js?

**Comment by AlexGalays** [comment]
@briancavalier No, not core developpers.

Imagine I have streams in my application that have a given lifecycle, say streamA is only created and subscribed from screenA, and same thing for streamB/screenB. How can I verify at a glance, that streamA is disposed when I go to screenB ? (perhaps because I have a streamA.until(ILeaveTheScreen))

**Comment by webOS101** [comment]
This is a question I have, too.  Say I have some component that needs to hook into mouse move on the document.  When the component is disposed of, how do I ensure that future moves don't try to call methods on my component?  I suppose you could use an `until()` and create some sort of stream to indicate component unload...  What's the best way to handle that?

**Comment by whitecolor** [comment]
I also think that ability could be added to support some more techical *utilitarian* not logical workflows:

for example here in my module https://github.com/whitecolor/cycle-hmr - hot reading for cycle.js
1) I make a proxy subscriptions (in quite a **imperative** manner) to the output streams of the dataflow component 
2) then component is reloaded I need to "replace" proxy stream subscription to new "version" of output (new stream from reloaded dataflow component), 
3) so first I subscribe to new outputs (not to loose multicasted sources "state")
4) then I unsubscribe from previous output streams - and this step is easy to do in other libs (rx, xstream) which allow to **imperatively** remove the listener (dispose subscription).

So in this terms:
> Most.js takes a declarative approach. Rather than an imperative approach

But when we use `observe` we actually attach listeners  **imperatively** why we can not remove them **imperatively** too?

**Comment by briancavalier** [comment]
I think we have a good solution now: 0.19.5 provides interop with the [draft ES Observable proposal](https://github.com/cujojs/most/blob/master/docs/api.md#draft-es-observable-interop).  So, you can use the [subscribe](https://github.com/cujojs/most/blob/master/docs/api.md#subscribe) method, which will return a Subscription that you can use to unsubscribe imperatively.

**Comment by whitecolor** [comment]
Hah, cool, @TylorS so probably then `subscribe` could replace `observe` in [most-adapter](https://github.com/cyclejs/most-adapter)?
