### ISSUE TITLE
Pushing events into a stream

### ISSUE THREAD

**Issue by sporto** [cujojs/most#149]
I'm looking at most.js as a great alternative for managing events in an application.

I would like to create a stream where I can push events manually. There is `most.create` but the way it exposes the `add` is quite awkward. I could something like:

```
var stream = most.create(function(add, end, error) {
    stream.add = add;
});

stream.add('event');
```

What about having a way to push events to an stream? Something like http://baconjs.github.io/api.html#bus

Thanks

**Comment by briancavalier** [comment]
Hey @sporto.  We've gone back and forth on this.  There are issues with imperative push APIs like the one you're proposing.  There's a [long thread on it here](https://github.com/cujojs/most/pull/72).  One of the most common issues is that it creates a situation where it is easy to miss events.  There are a couple comments in that thread that discuss this issue specifically: [here](https://github.com/cujojs/most/pull/72#issuecomment-102392832) and [here](https://github.com/cujojs/most/pull/72#issuecomment-106651974).

I'm still not entirely opposed to it--I just want to make sure it's worth committing to, and that the tradeoffs are worthwhile, since it's harder to remove an API than to add one :)

Could you describe the use cases where you feel you need this kind of imperative push vs. most.js's other, safer ways of producing streams?  Thanks!

**Comment by sporto** [comment]
@briancavalier 	I am developing a new React / Flux application and I was thinking about using most to manage my events.

Commands in my application will push events to a most stream, the stores listen to those stream.
When a store changes it would be published to a most stream, components will listen to those stream to re-render. 

I realise that this might not be the main aim of most.js (other libraries like js-signals seems to be more suitable). But the thing I really like about most is `debounce`. I will like to use this so too many changes in stores are debounced before hitting the components. Also other interesting patterns could by using most.

**Comment by PhiLhoSoft** [comment]
Bacon.js' author himself is defiant about the usage of bus: http://baconjs.blogspot.fr/2014/12/bus-of-doom.html

I am not pro or against the feature, I just add information to the debate... :grin:

**Comment by spro** [comment]
@sporto I was looking for the same thing and just put together https://github.com/spro/most-bus which mimics Bacon's API of `.push` and `.plug`... a bit of a hack but it seems to work.

**Comment by briancavalier** [comment]
most.js likely won't include an imperative push adapter directly (other than `most.create`). However, there are now several options, such as @spro's `most-bus` and @TylorS's [most-subject](https://github.com/TylorS/most-subject).

Closing this, but please feel free to continue to discuss or reopen if needed.

**Comment by spro** [comment]
Future travelers: I'm deprecating `most-bus` in favor of @TylorS's `most-subject`, which has a better interface and tests.

**Comment by briancavalier** [comment]
Thanks for the note, @spro!

**Comment by TylorS** [comment]
Thanks for `most-bus` though, it helped me get started on my journey @spro
:+1:
