### ISSUE TITLE
Debug advice for fromEvent

### ISSUE THREAD

**Issue by jasonkuhrt** [cujojs/most#153]
##### Works:
```js
    redisSubscriber.on('pmessage', () => {
      console.log('From EE', arguments)
    })
```

##### No Works:
```js
    FRP
    .fromEvent('pmessage', redisSubscriber)
    .tap(() => {
      console.log('From FRP', arguments)
    })
```

Why might the `Most` variant not be working? If the EE (EventEmitter) variant is working just fine, what could be going wrong by definition (e.g. the API is essentially declarative, nothing to "screw up")?

Thanks!

**Comment by jasonkuhrt** [comment]
to clarify "No Works" means no feedback at all, the events never come through. I've done the sanity checks like making sure `most` thinks `redisSubscriber` is an `EventEmitter` etc.

**Comment by briancavalier** [comment]
Hey @jasonkuhrt.  Most streams are inert when there is no *demand* for the items they contain.  To create demand, someone must consume the stream using [`observe`](https://github.com/cujojs/most/blob/master/docs/api.md#observe), [`reduce`](https://github.com/cujojs/most/blob/master/docs/api.md#mostcreate), or [`drain`](https://github.com/cujojs/most/blob/master/docs/api.md#mostcreate).

In your example, since the stream is technically only being *transformed* (by `tap` which is effectively an identity transformation), but not *consumed*, it is inert, which explains why there's no feedback: there is absolutely nothing happening because there is no need (i.e. no demand) :)

Here's a modified version of your example you can try:

```js
import { fromEvent } from 'most';

fromEvent('pmessage', redisSubscriber)
    .observe(() => console.log('From FRP', arguments))
```

I hope that all made sense and helps!

**Comment by jasonkuhrt** [comment]
@briancavalier Absolutely. To be clear then, it is accurate to state that only this functions https://github.com/cujojs/most/blob/master/docs/api.md#consuming-streams trigger changes in the stream's subscriber count?

**Comment by jasonkuhrt** [comment]
Ah, you said as much

> To create demand, someone must consume the stream using observe, reduce, or drain.

Cool, thanks again!

**Comment by briancavalier** [comment]
No problem. Happy to help.
