### ISSUE TITLE
Combining multiple streams into an object

### ISSUE THREAD

**Issue by TylorS** [cujojs/most#165]
Hello again!

I'm looking to solve combining multiple streams into an object

Something along these lines:

```js

const a$ = most.just('a');
const b$ = most.just('a');
const c$ = most.just('c');

const d$ = most.someMethod(
  a$, b$, c$,
  ( a, b, c ) => ({ a, b , c })
)
```

I was looking at the zip method, but I'm unable to get it to work just right.
Thanks for your help!

**Comment by TylorS** [comment]
Maybe I should clarify, that I'm trying to get their values into the object, not just an object of streams.

**Comment by TylorS** [comment]
Sorry for the spam, I was able to solve this with zip.

**Comment by briancavalier** [comment]
Hey @TylorS.  Time is an integral part of event streams, i.e. an event is a value associated with a particular instant in time.  Because of that, there are several ways to combine multiple streams.  One way is `zip`, which aligns two streams based on event *index*.  That sounds like what you want.  Could you show what you tried and maybe we can figure out why it didn't work?

Here's a quick example to show zip working.  It generates pairs of numbers in an object:

```js
var s1 = most.iterate(inc, 0);
var s2 = most.iterate(inc, 1);

most.zip(function(a, b) { return { a:a, b:b } }, s1, s2)
	.observe(console.log);

function inc(x) {
	return x+1;
}
```

**Comment by briancavalier** [comment]
Haha, jinx :)

**Comment by TylorS** [comment]
What are the chances! It turns out one of my values was getting passed around as an array and ruined everything for everyone else :+1: 

Thank you though for the reply

**Comment by briancavalier** [comment]
Glad you were able to solve it.  One note about zip:  Because it aligns events based on their *index*, if you zip two streams of different speeds, it can cause unbounded buffering.

For example:

```js
var s = most.zip(f, fast, slow);
```

In that case, events in fast will build up in a buffer until the corresponding events in slow arrives.  If fast and slow are infinite, the buffer will eventually consume all available memory :)

As long as, over time, the two streams proceed at relatively the same rate, or they're short-lived enough that buffering isn't a problem, you'll be fine.

**Comment by TylorS** [comment]
Thanks for that clarification, is there a better way to do it without running into that issue? I'm using it for something that could update thousands/millions of times (theoretically)

**Comment by TylorS** [comment]
So to clarify I'm trying to do some transposition. This is simplified

```js

function combineVTreeStreams( vTree, ...children ) {
  return Object.assign( vTree, { children });
}

function parseTree( obj ) {
  return Most.zip(
    combineTree,
    Most.just( obj ),
    ...obj.children.map( parseTree ) // array of 'obj's
  )  
}

obs
  .flatMap( parseTree )
  
```
