### ISSUE TITLE
Most.zip() buffering issue.

### ISSUE THREAD

**Issue by TylorS** [cujojs/most#166]
I was successful in being able to get a cycle.js port to most and with the snabbdom virtual-dom library doing UI rendering. I was able to find significant speed improvements with most! I'm unbelievably excited!

However in my benchmarking, I've really run into the issue of `most.zip()` backing up and 'freezing' the UI. Is there a way workaround for this or a more performant operator?

**Comment by briancavalier** [comment]
Cool!  I'd love to check out what you've done.  Can you share?

>  Is there a way workaround for this or a more performant operator

It's not really about performance, *per se*.  Zip is doing what it must do in order to align events by index.  When you have a fast producer and a slow producer, there's really only a few choices: ask the slow producer to speed up (not an option here?), buffer events, drop events, or ask the fast producer to slow down.

A demand-aware implementation (aka back pressure) might be able to do the latter (as long as the source of the events was also demand-aware), but most.js doesn't support that right now.  It may in the future, but not really sure yet if we'll go in that direction.

We could introduce some sort of buffer retention policy in a zip variant.  But that would mean being willing to drop some events in the case where the zip buffer gets "full" (for whatever definition of "full" the retention policy implemented).

Zip is the only problematic combinator wrt forcing buffering, so maybe there is another way of combining streams that would work?

**Comment by TylorS** [comment]
Okay that's what I thought. I'd love to share and hear what you think!

Core : https://github.com/tylors/cycle-more
Snabbdom driver : https://github.com/tylors/cycle-more-snabbdom
And here's a performance test we use in the 'official' Cycle-DOM driver ported to these 2 libraries.https://github.com/tylors/cycle-more-snabbdom-perf-test

**Comment by TylorS** [comment]
I use `zip()` in bother the snabbdom driver and the test. They are a large part of my call stack, and I'm running into the issue you mentioned, on the other issue, I'm pretty sure in the test code. But speeding up or slowing down isn't really an option since rerending needs to be minimized for performance and it needs to be, in my opinion, a perfect reflection of application state.

**Comment by TylorS** [comment]
Also the slow producer in my case, and in many others, is that it never actually changes.

**Comment by briancavalier** [comment]
> never actually changes.

Hmm, do you mean the slow produce contains exactly 1 event?

**Comment by TylorS** [comment]
In this case it should be, but not in all.

**Comment by briancavalier** [comment]
Ah, interesting, thanks.  A bit more info, and then more questions :)  maybe we're on to something here.

Zipping a stream containing exactly 1 event with a stream containing > 1 event will always yield a stream containing exactly 1 event.  IOW, the proportion of the zipped stream is the same as the proportion of its smallest input stream.  The trickiness is around time.  If you have an input stream containing 1 event, but that event is far in the future, and the other input stream's many events are much earlier, zip still has to buffer.

And now a couple more questions (for now assuming you have a 1-event stream, even though in some cases, as you say, it may not be exactly 1):

1. Is the 1 event far in the future compared to the many events in the other input streams, or are the close in time?  For example:

```
Does the situation look like this?
s1: ---------------------------------------------------------------------a->
s2: x-y-z-...>

// Or more like this?
s1: -a->
s2: x-y-z-...>

2. Is your intention to pair the 1 event with only the first event in the other input streams, or is it to pair that 1 event with *each* event in the other input streams?  I'll abuse haskell notation here to try to show what I mean:

```
// Given this and zipping s1, s2 by applying f
s1 = [a]
s2 = [x,y,z]

// Do you want this?
zipped1 = [(f a x)]

// or this?
zipped2 = [(f a x), (f a y), (f a z)]
```

**Comment by TylorS** [comment]
I may be wrong, but I believe I want zipped2.

Basically I have `<input type="range" step=25 min=0 max=500 />` ( rendered
by snabbdom ) and as I move it up and down I render `n` number of a
component based on the inputs value. If I move it slowly it works great,
but if I slide it quickly after 5 steps it locks up

**Comment by briancavalier** [comment]
@TylorS Ah ha, ok, we're definitely on to something.  zipped2 is actually a different operation ... zipped1 is what most.zip will give you--the "classic" definition of a zip.  zipped2 is what [most.combine](https://github.com/cujojs/most/blob/master/docs/api.md#combine) will give you.  It pairs the *most recent* event from s1 with the *most recent* event from s2.  Because of that difference, it never needs to buffer.  So, if zipped2 is what you want, give most.combine a look.

**Comment by briancavalier** [comment]
> never needs to buffer

Oops, not *technically* correct.  It will never retain more than N-1 events at any given time, where N is the number of input streams.  So `most.combine(f, s1, s2)` will retain 1 event.

**Comment by TylorS** [comment]
Wonderful! I'll get back to you on that as soon as I can, likely tomorrow.
Thanks for being so helpful!

I also hope to hear what you think about Cycle and Most brought together.
Feel free to ask me as many (or more) questions as I've been asking you
:smile:

Thanks again!

**Comment by briancavalier** [comment]
Yeah, let me know how it goes.

I spent a bit of time today reading the cycle.js docs to really understand the concepts.  Seems quite interesting, very reminiscent of FRP networks, so def want to dig more into cycle-more :)  I should have time this weekend to take a closer look.

**Comment by TylorS** [comment]
Great! While you're here, is there a better place for me to ask these kinds of questions? I don't want to flood the issues here as I better learn most.

**Comment by briancavalier** [comment]
Sure, you can ask on [gitter](https://gitter.im/cujojs/most).
