### ISSUE TITLE
Roadmap, enhancements and contribution?

### ISSUE THREAD

**Issue by axefrog** [cujojs/most#179]
A few things:

1. Am curious if you have a roadmap that I haven't noticed, or which is not currently visible
2. Any plans to move the library over to the mostjs organization so that it can be stand alongside relevant extensions and utilities?
3. Any scope for contributors to help you get the library over the line?
4. Would like to suggest exposing *everything* externally. As an example, I'm trying to make an overload of `reduce`, and have no way to access the `Accumulate` constructor.

**Comment by briancavalier** [comment]
Hey @axefrog!

> roadmap that I haven't noticed

Unfortunately, I haven't written it down anywhere, though @davidchase and I have discussed a few things.  Bug me about it on gitter sometime, and I'll be happy to discuss.

> Any plans to move the library over to the mostjs organization

Yeah, we should, though it's not quite clear yet what form that would take.  For example, @davidchase and I have talked about creating `@most/core`, which contains some minimal amount of the most core plus only the most essential combinators (like map and filter).  Then, `most` proper could depend on `@most/core`.

Any thoughts on that approach?

> Any scope for contributors to help you get the library over the line?

I def welcome contributions.  This is, of course, related to the roadmap, which we can discuss on gitter.  I think a good goal would be to write down the roadmap and identify items where contributors could jump in.

> Would like to suggest exposing everything externally

I do think most needs to expose some slightly more primitive public APIs.  However, I consider `Accumulate` and classes like it to be implementation details.  I would prefer to use functions instead, but that would require lots of scope chain capturing which would change the performance (cpu and memory) characteristics of the whole library.  I'd rather expose more primitive functions (implemented using `Accumulate` and the like) which allows generalized accumulation (or at least "more configurable" accumulation), rather than exposing these implementation detail classes.  Once we expose a constructor like `Accumulate`, it becomes extremely difficult to change or remove it.

I guess what I'm saying is that it feels more like there is a missing, slightly more general, public API.  I would prefer to fill that hole rather than expose the even-more-low-level implementation classes.

**Comment by TylorS** [comment]
> @most/core, which contains some minimal amount of the most core plus only the most essential combinators

I like this idea a lot for whatever it is worth. Maybe it would be a good place to implement the ES7 observable specification, while the other operators are "extras". Just and idea

>  I think a good goal would be to write down the roadmap and identify items where contributors could jump in.

:+1: I think this is a good idea as well, for any project.

**Comment by briancavalier** [comment]
see #180

**Comment by briancavalier** [comment]
> I'm trying to make an overload of reduce

@axefrog I think this is the one item in your list that isn't covered by #180 yet.  Could you provide a bit more detail on the kind of accumulator you'd like to be able to create?  Left fold (aka reduce, or foldl) is pretty well defined. There are variations such as foldl1, associative and commutative folds, and CPS folds, though I'm not sure if any of those apply to a time-based event stream.

Thanks!

**Comment by axefrog** [comment]
Hey, sorry for the delayed reply. Been a bit swamped. Actually my particular case was just that I needed to run `reduce` with a test scheduler and there was no way for me to do that without reimplementing the operator myself.

**Comment by briancavalier** [comment]
@axefrog got it, thanks!  I'll add a note to the roadmap.

**Comment by briancavalier** [comment]
Closing this in favor of #180, but if there's something here that you think isn't represented on the roadmap, please say so!
