### ISSUE TITLE
Is there any support for fromNodeCallback 

### ISSUE THREAD

**Issue by tusharmath** [cujojs/most#214]
How does one quickly integrate with node.js functions such as `fs.read` ?

**Comment by briancavalier** [comment]
Hi tusharmath, you could use [`most.create`](https://github.com/cujojs/most/blob/master/docs/api.md#mostcreate) to integrate with `fs.read`.  Although, `fs.read` is a bit of a different beast in the node world, since you typically would end up calling it repeatedly with different parameters.  It should still be fairly simple, though.

**Comment by tusharmath** [comment]
I would take that answer as a no. Thanks.

**Comment by TylorS** [comment]
@tusharmath It's quite easy to create new stream sources. Here's a link to a sample fromNodeCallback source.

https://gist.github.com/TylorS/00e37b84498c78f2da3bcd948495f2fd

**Comment by partially-applied** [comment]
@tusharmath  

For node.js style callbacks and modules like `fs` see if this helps :

https://github.com/partially-applied/mostify

Its not part of most core, and I think its good to keep it separate, the worst thing that can happen is most turns into bloatware like rxjs.
