### ISSUE TITLE
Steps to migrate from Rx

### ISSUE THREAD

**Issue by tusharmath** [cujojs/most#266]
The performance seems promising and I am really keen about migrating from Rx4. Are there any migration documents that one could follow or some way to just simply start using it?

**Comment by briancavalier** [comment]
Hey @tusharmath!  

There are a lot of similarities between the two libraries, since they are both based on the notion of an asynchronous sequence of events over time.  I think you'll find that many of the concepts you know from using Rx will apply when using most.

There are also differences, of course, from the APIs down to the internals.  Most focuses on providing a smaller set of high performance core operations, i.e. building blocks.  For example, if you've used Rx's `switchMap(f)`, which is mapping and then switching, in most.js you'd do `.map(f).switch()` ... i.e. building blocks.

Here are some resources that may help you get started:

1. [API docs](https://github.com/cujojs/most/blob/master/docs/api.md)
2. [New examples repo](https://github.com/mostjs/examples) (there are [older versions of some examples](https://github.com/cujojs/most/tree/master/examples) in the most repo, but those are being moved to the new repo).  More examples are coming.
3. [This great document](https://github.com/ivan-kleshnin/reactive-polyglot) (ht @ivan-kleshnin) showing equivalent operators from several reactive libs, including most and Rx.

Also, even though you don't need to read it to use most, you may find the [architecture document](https://github.com/cujojs/most/wiki/Architecture) to be interesting as well.

I'm glad we got to chat a bit on gitter the other day.  Please do feel free to ask specific questions either there or here.
