### ISSUE TITLE
feature: most.create for nodejs style callbacks

### ISSUE THREAD

**Issue by jadbox** [cujojs/most#267]
Node has the below style of async API for their ecosystem. Seeing the most.create is going to be moved into its own project, can we get a simple/clean way to provide Node async functions to it to create a stream source? e.g. `most.fromNodeCallback(myAsync)`
```
function myAsync(val, cb) {
   const err = null;
   const result = "success";
   // do something async
   cb(err, result); // may be called once or multiple times
}
```

**Comment by jadbox** [comment]
Also, I'd like to avoid needing another library (like bluebird) to wrap the functions into promises for `most`.

**Comment by jadbox** [comment]
Here's a rough Node alternative to `create`- haven't tested it yet:
https://gist.github.com/jadbox/8fed38ae730e8fb6a909edb9f6deae0c

**Comment by briancavalier** [comment]
Hey @jadbox.  Thanks for posting the gist.  The direction we're taking now is to keep the most core package lean and focused on pure operations, and to make it easy for folks to publish a la carte packages for functionality like your `fromNodeCallback` and `flatMapNode`.

BTW, `most.create` is not going away, it will simply move to another package.  So, you'll still be able to use it.  So, I can think of a couple options:

1. You could publish those now using `most.create` (with most as a peerDep).  When the new package containing `most.create` is available, you could switch your package to use that

2. You could implement and publish those functions using [most's Source and Sink](https://github.com/cujojs/most/wiki/Architecture) architecture in a more efficient way than using `create`.  This may sound more intimidating, but it's actually quite simple.  

Either way, join us in [the gitter chat](https://gitter.im/cujojs/most) and we'd be happy to help!

**Comment by TylorS** [comment]
@jadbox It could possibly look like this: https://gist.github.com/TylorS/00e37b84498c78f2da3bcd948495f2fd

**Comment by jadbox** [comment]
I'm curious why the Src/Sink method would be faster than `most.create`? 
Would native Node support be important enough to put into core?

@TylorS Thanks for the example!

**Comment by briancavalier** [comment]
> Would native Node support be important enough to put into core?

My first instinct is that it should be a separate package, e.g. `@most/node` or something fairly obvious like that, but I'm open to discussing it.  Browser apps likely wouldn't need it 90% of the time, so being able to add it to a project a la carte is appealing.

Thoughts?

> I'm curious why the Src/Sink method would be faster than most.create?

All most streams make the same guarantee: the function you pass to `observe/forEach/reduce will not be called before observe/forEach/reduce returns.  There are really two options for making that guarantee in `most.create`, either 1) wait for the stack to clear before calling the producer function passed to `most.create`, or 2) buffer events and propagate them after the stack clears.

Originally, it did 1, which proved to be confusing for users, so we switched to 2.

Since node functions already are async (well, they *should be* anyway!), by their very nature they would not propagate an event before the stack clears.  So, there is no need to a lot of the buffering gymnastics that `most.create` does ... it'd just be adding overhead for no reason.

There are a few other more minor factors.  For example, `most.create` creates 3 closures to pass to the producer function.  A node solution probably would only need 1.  Also, because `most.create` is a general purpose solution, it has to do more generalized error handling.  That means it uses try/catch in several places, which prevents the VM from optimizing several functions.

On the other hand, using Source/Sink directly is more "bare metal".  A node solution with Source/Sink would not need to do buffering, could create fewer closures, and could do error handling in a way that is more tailored to node style functions.

**Comment by jadbox** [comment]
@briancavalier thanks for the clear explanation!

I'm torn if Node cb support should be in core. However, I can foresee Most becoming popular for Node due to the performance, and `fromEvent` is in core yet it is really used for browsers.

**Comment by briancavalier** [comment]
Hey @jadbox, sorry for not responding for a bit.  I think I like the idea of creating a separate package.

`most.fromEvent` is a bit of an outlier.  It was created before we had formed our current direction of keeping the core lean and adding platform or environment specific sources/adapters in separate packages.  Now we have [`@most/dom-event`](https://github.com/mostjs/dom-event), which is a much nicer API for DOM events (somewhat ironically, `most.fromEvent` *also* supports node's EventEmitter!).

Would you be interested in helping out with a node-related package?

**Comment by partially-applied** [comment]
Hey @jadbox  

I have been having the same issue as you ! and it seems like a general problem even in my workflow. I tried different techniques. One Major headache is input tracking. 

https://github.com/partially-applied/mostify

I created this tiny module to take care of both the problems, hope you like it !

**Comment by briancavalier** [comment]
@jadbox Now that @partially-applied has created [mostify](https://github.com/mostjs-community/mostify), and `@most/create` is available as an a la carte package, I feel like there are good solutions out there for now.

So, I'll close this, but please feel free to continue discussion here.

**Comment by jadbox** [comment]
Okay, thanks @briancavalier
