### ISSUE TITLE
switch does not propagate cancel requests across switch boundary?

### ISSUE THREAD

**Issue by ntilwalli** [cujojs/most#300]
When `switch` swaps the new stream with the old the cancel propagation terminates on a switch boundary, so if the inner stream was itself created through a `switch` operator, the inner stream associated with the inner `switch` is never canceled.  This is different than the behavior in both Rx 4 and xstream.

most: http://www.webpackbin.com/4kP1_KOu-
Rx 4: http://www.webpackbin.com/VyEKDF__W
xstream: http://www.webpackbin.com/Ny5VwFdOZ

Isn't this a bug?

**Comment by axefrog** [comment]
The cancellation and propagation behaviour you're expecting is the wrong way to think about things; it's not quite how most works. Every stream in most has a single `source`, which contains a function `run(sink, scheduler)`. When you use most's fluent API, what happens is that the `source` property of the stream is extracted, passed to the fluent API method you've called, and a new stream is returned, usually with a new `source` property which retains the old source somewhere internally.

When you call `observe`, `drain`, `forEach` or `reduce` on the final stream you've composed, internally the first `source` object's `run()` method is called, passing in a sink object created by the observation method you used. The `run()` call returns a disposable object. When run is called, what you're saying is that the upper source may now emit events to the specified sink in perpetuity until you call the returned disposable. Most sources (except for producer sources, which are up the top of the stream) will tend to call run on their own sources, and pass in a sink of their own. That sink will usually be dynamically constructed and it will generally wrap the downstream sink.

The sink object has the methods `event()` (for data), `end()` and `error()`. If the upper source decides to terminate the sink proactively (for example because of `take(3)`, terminating after 3 events have been emitted), then it'll call the `end()` or `error()` method on the sink, and the sink will propagate that downstream, calling the same method on the sink(s) it wraps, and then activate the disposable that `run` returned.

**So what is `switch()` doing?**

The first thing is that it is a higher order source. It expects its upper source to emit streams. When it receives a stream, if it already had an active inner stream, it simply calls `dispose` on that stream and discards it. It then calls `run()` on the new stream, passing its own internal sink to the run method. When the internal sink receives and `end` event, it doesn't propagate that downstream, because that would cause the entire chain to end, and `switch` is only concerned if the outer upstream source has ended. Instead, it will just dispose the inner stream and wait for a new one fto be received from upstream. If the inner sink receives an `error` signal, then it *will* propagate that downstream, because an error event is indicative of overall stream failure, and that must be able to be dealt with. And of course any `event` (data) signals received by the inner sink will propagate, because that's the point of `switch`.

If you want to terminate the inner stream that is active within `switch`, then simply remember that the inner stream will only be discarded by `switch` if it either receives an `end` signal from its own upstream source, or if `switch` is disposed from downstream because of something like a `take` operator reaching its event limit. Even if `switch`'s upstream source ends, switch won't end until the active inner sink ends, and at that point the `end` signal from the inner sink *will* be propagated downstream.

So again, to terminate an inner stream, define the termination condition as part of that stream, for example using `takeUntil()`, or implicitly terminate it by having another stream arrive from upstream of `switch`, which will cause the existing active inner stream to be disposed.

**Comment by briancavalier** [comment]
@ntilwalli Your example seems potentially interesting.  However, there are a couple things about it that make it harder to understand what is going on and whether there's actually a problem.  First, there's just a lot going on in it, and second, it's fairly different from either the rx or the xstream examples.  Could you try to simplify it, i.e. try to find a more minimal example of the problem you think you're seeing?  I think that will help us figure out what's going on.  Thanks!

**Comment by ntilwalli** [comment]
I've reformatted the examples above to make the equivalences more apparent (hopefully).

**Comparison (with switched inner stream)**
_most_: http://www.webpackbin.com/EJ-A3xFu-
_rx 4_: http://www.webpackbin.com/E1Ncqet_-

**Comparison (without switched inner stream)**
_most_: http://www.webpackbin.com/N1m3agYub
_rx 4_: http://www.webpackbin.com/4J3q0lFuZ

The question is whether having switched inner streams should change the behavior of the output.  In Rx you can see it doesn't matter, as it currently stands (at least for this specific example), in most, it does.  I'm not arguing that all four example outputs should be the same, but that for each library the the output should be consistent between having the switched internal stream and not.

**Comment by ntilwalli** [comment]
@axefrog thank you for the explanation.  In the examples above, when the a stream is `switch`ed off from downstream, it is disposed, which means it's upstream sources that have only one listener should be disposed too, including switched sources and their inner streams.

**Comment by ntilwalli** [comment]
Here is another example which is more representative of the Cycle component I'm building.  http://www.webpackbin.com/Vyh9MWF_Z

The inner sinks in this example are sourced using a periodic` but in my app they're sourced from DOM event streams (`DOM.select(...).events(...)`).

**Comment by ntilwalli** [comment]
Even simpler examples posted below

**Most**
__with internal switched streams__: http://www.webpackbin.com/E1jVwaKO-
__without internal switched streams__: http://www.webpackbin.com/4JAUD6YOb

**Rx 4**
__with internal switched streams__: http://www.webpackbin.com/E1q8YTFuW
__without internal switched streams__: http://www.webpackbin.com/EyBUtaF_b

**Comment by briancavalier** [comment]
@ntilwalli Thanks for all the additional info.  I haven't had a chance to dig into it, but it seems like there's some sort of race condition related to the end of stream handling in switch.  I should have time soon to look into it more.

**Comment by briancavalier** [comment]
@ntilwalli I just pushed a candidate fix in #303.  Could you try the [fix-switch-dispose branch](https://github.com/cujojs/most/tree/fix-switch-dispose) and see if it works for you?  Thanks!

**Comment by ntilwalli** [comment]
@briancavalier Looks good!

**Comment by sourcevault** [comment]
I have created an example trying to recreate the issue, is this expected behavior ? : 

```ls
most.periodic 1000
.take 2
.map ->
  $ = most_create (add,end,error) ->
    I = setInterval add,1000
    ->
      console.log "from outer dispose"
      clearInterval()
      end()

  $.map ->
    most_create (add,end,error) ->
      J = setInterval add,1000
      ->
        clearInterval()
        console.log "from inner dispose"
        end()
  .switchLatest()
.switchLatest()
.drain()
```
real output :
```
from outer dispose
from inner dispose
from inner dispose
from inner dispose
from inner dispose
from inner dispose
```

**Comment by sourcevault** [comment]
Alright boys !

I can with 100% guarantee say that `most.js` calls the inner dipose of the inner `switchLatest`

So if you have an outer `.switchLatest()` and an inner `.switchLatest()` then any inner `dipose` gets executed when the inner stream is discarded. 

<img width="553" alt="stream" src="https://user-images.githubusercontent.com/20347647/107873405-8c431880-6edc-11eb-98fb-40e32e265334.png">

from my first project (`remotemon`) that uses `most.js `operationally, notice the text ;

`[[[ watcher closed on proc ]]]` that is the inner `switchLatest()` created using `@most/create`.

Cheers ! ☺️
