### ISSUE TITLE
Support for Virtual Time Scheduling

### ISSUE THREAD

**Issue by tusharmath** [cujojs/most#343]
RxJS has a wonderful abstraction when it comes to scheduling using TimeSchedulers. The major advantage of it is that we can control how time flows across the system without it having any relation with the actual CPU time. This is particularly useful for unit testing where u don't want to wait unnecessarily for the real time to elapse before you can assert your output.

So here is my proposal —

We pass a `Scheduler` object as the second param to the `Observable`'s  `subscribe` function. 

**Observable**

``` ts
export interface Observable<T> {
  subscribe(observer: Observer<T>, scheduler: Scheduler): Subscription
}
```

The scheduler is going to be a singleton and since every operator/combinator internally subscribes to some other sources they too pass the received scheduler to those sources. Essentially we have a single instance of the Scheduler shared across the application thus maintaining a central control over time.

**Scheduler**

``` ts
export interface Scheduler {
  setTimeout(cb: Function, relativeTime: number): Disposable
  setImmediate(cb: Function): Disposable
  setInterval(cb: Function, interval: number): Disposable
  requestAnimationFrame(cb: Function): Disposable
  now(): number
}
```

Schedulers provide the standard javascript timing functions such as `setTimeout` , `setImmediate` etc. and also the current time of the scheduler via `now()`. The implementation of these timing functions would be left to the class that implements the  `Scheduler` interface. For instance the `DefaultScheduler` could use the actual JS event loop to asynchronously queue jobs where as a `TestScheduler` could have its own implementation of the queue using arrays that is synchronous.

**Comment by briancavalier** [comment]
Hi @tusharmath.  This got a little long-winded, sorry :)  So, here's a quick summary:

1. most.js Scheduler is a different thing than RxJS Scheduler (unfortunate naming overlap is my fault).
2. most.js supports virtual time for testing: check out @axefrog's [most-test package](https://github.com/mostjs-community/most-test).
3. I'm interested to hear your thoughts on custom Scheduler use cases beyond testing (keeping in mind 1 above).  I've not yet encountered any compelling ones.

---

Finding the right way to expose a configurable scheduler while also providing a sensible default has been a long topic of discussion.  First, it's important to remember that Scheduler in most.js is a very different thing than Scheduler in RxJS.  The naming overlap is unfortunate!  Sorry for any confusion.  A Scheduler in most.js manages a well-ordered Timeline of Tasks based on a Clock.  It's API intentionally has no notion of requestAnimationFrame, or timeouts vs immediates, etc.  Those are implementation details of a particular Scheduler instantiation.

Another similar (but subtly different!) topic is that of *moving work* to another JS "thread" (or, in most cases, another work queue, such as rAF).  For example, it typically wouldn't be good to run your entire stream graph in the rAF queue.  Rather, it can be useful to move certain bits of rendering logic to rAF.  This is not the intent of Scheduler.

Ok, with that in mind, discussions around virtual time scheduling always seem to come to a similar conclusion, which is that there are two big categories of scheduling tasks in the most.js world: wall-clock time for apps, and virtual time for testing.

So, your point about using virtual time instead of wall-clock time for testing is a good one.  Currently, most.js does this in its own unit tests by implementing a custom VirtualClock, instantiating a Scheduler with it, and then running streams using that virtual time Scheduler.

@axefrog took that idea, and created the very awesome [most-test package](https://github.com/mostjs-community/most-test), which anyone can use to test streams with virtual time.

Beyond testing, I've not seen a compelling use case for a custom Scheduler (or it's friends, Timeline and Clock).  Do you have use cases that might benefit from one?  If so, I'm certainly interested to hear about them.

Hope that helps!

**Comment by tusharmath** [comment]
@briancavalier 

I totally resonate with your explanation above. I have seen the _**most-test**_ package and that's really cool too, but when I use other timing functions in js, I find it nearly impossible to test my code  —

```js
function testable (a$, b$, c$) {
  const source$ = most.merge(
    a$.debounce(10),
    b$.debounce(100),
    c$.debounce(15)
  )

  // RAFThrottle throttles using requestAnimationFrame
  return RAFThrottle(source$)
}

```

`RAFThrottle` would be my custom implementation of a throttle function which throttles tasks using `requestAnimationFrame`. The effect of `debounce` can be tested using **most-test** but how do I mix it up with `requestAnimationFrame`?

**Current Solution**
Pass an additional param say — _rafScheduler_ to `RAFThrottle`, that can be mocked while testing and defaults to a value otherwise —

```js

// rafScheduler is undefined while not testing
function testable (a$, b$, c$, rafScheduler) {
  const source$ = most.merge(
    a$.debounce(10),
    b$.debounce(100),
    c$.debounce(15)
  )

 // rafScheduler could be undefined, in that case a default implementation would be used by RAFThrottle
  return RAFThrottle(source$, rafScheduler)
}
```

The obvious problem here is that the `rafScheduler` is going to get really complicated because it needs to be in sync with the **most-test**'s _virtual time_ . Also, now this param needs to be moved around everywhere `testable` is being used, that's clutter in my opinion :(

If the most.js scheduler could provide all the JS timing functions directly it would be really easy to write my custom operators and schedule tasks using them. For instance in the above case I would have  two kind of implementations for `requestAnimationFrame` — 1. using the native implementation and 2. Using virtual time of `16.77ms`. That way  I can now use **most-test** to test the stuff that is being queued using `requestAnimationFrame`. Since the schedulers are provided at run time, my code would too not need any change and would stay like the first version.

The same issue arises when we schedule using `setImmediate` or `requestIdleCallback` etc. and should be a part of the scheduler API in IMHO.

**Comment by TylorS** [comment]
I have to say I'm pretty opposed to the proposed added methods to the Scheduler. 

[`setImmediate`](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate) is non-standard and is never expected to become a standard.

`setTimeout` is pretty unnecessary because this behavior can already be achieved with `scheduler.delay`.

`setInterval` is also quite unnecessary because this behavior is already achieved with `scheduler.periodic`.

`requestAnimationFrame` and `requestIdleCallback` are only available in browsers, and can not be used on platforms such as node.js.

---

I don't think what you're trying to accomplish is unreasonable, but I don't feel added methods to the scheduler is the right answer.

**Comment by briancavalier** [comment]
@tusharmath I think @TylorS outlined very sensible reasons why it doesn't make sense to modify scheduler in the way you're proposing.  Scheduler has a focused purpose, and I don't want to turn it into a more complex layer that attempts to abstract all possible queueing functions on all possible JS platforms.

That said, it sounds like your goal is to move work to the raf queue.  That's a perfectly reasonable thing to do.  Since you mentioned "throttling", it also sounds like you expect your events to occur more often than raf, on average.  In that case, sampling with a raf-based stream could be a good option.  If you expect the events to occur less often than raf, then simply scheduling the work onto raf yourself would be a good solution.

As for testability, creating a source that is parameterized by "set" and "cancel" functions could be a good and simple solution.  As a starting point for such a thing, have a look at [this animation frames stream](https://github.com/briancavalier/most-behavior/blob/master/src/animationFrames.js) I created for another experiment (you can see how I used it to [sample something and do rendering on raf](https://github.com/briancavalier/most-behavior/blob/master/examples/bounce/index.js#L102-L103)).  You could probably modify that fairly easily to create a parameterized source that allows you to provide test functions or real rAF/cAF in an app.

I could see a simple rAF stream being a useful thing for the community.

**Comment by tusharmath** [comment]
Closing the ticket as it seems reasonable to me at the moment to not incorporate the above changes in most.js.
