### ISSUE TITLE
Feature Request: await tap

### ISSUE THREAD

**Issue by dypsilon** [cujojs/most#348]
Hello everyone,

right now the "tap" documentation reads:

`Perform a side-effect for each event in stream.`

Since it's a function which is primarily aimed at running side-effects, I would expect it to provide some await mechanics. Example implementation: if the provided function returns a Promise, wait until its resolved, discard its value and then go on with the stream.

Hope such feature makes sense.

Cheers

**Comment by briancavalier** [comment]
Hi @dypsilon!  This makes sense, and sounds like it could be a useful alternative, although perhaps more of a niche operation.  I'd be interested to see if others in the community have encountered a need for it.  Perhaps we can discuss in the gitter chat and see.  Would be interested to hear if @TylorS and @davidchase have encountered use cases for this as well.

One way to do it with no change to most.js is to tap promises, and use map + await instead of tap + await:

```js
// "async tap" a promise
const tapPromise = f => promise =>
  promise.then(f).then(() => promise)

const doAsyncSideEffect = (...) =>
  // perform some side effect and return a promise

const tappedStream = stream.map(tapPromise(doAsyncSideEffect)).await()
```

This could be wrapped into a simple API, perhaps as a new [mostjs-community](https://github.com/mostjs-community) project, if you are interested in contributing.

**Comment by davidchase** [comment]
This is quite interesting... although don't think i have a use case for it just yet.. this would be a nice addition to the community as Brian mentions above.

**Comment by briancavalier** [comment]
@dypsilon How often do you find yourself in need of this await tap operation?  Any thoughts on this as a mostjs community add-on?

**Comment by EricCrosson** [comment]
I've been poking around the most docs and now old issues to learn more about it -- seems like one of the goals of most is a [small API surface](https://github.com/cujojs/most/issues/228#issuecomment-407740059), so the idea of an asynchronous tap seems like it would be best placed in the community repos as suggested above.

Would you consider this issue a good candidate to close on account of lack of recent activity?

**Comment by briancavalier** [comment]
Now that [@most/core](https://github.com/mostjs/core) is the recommended package, it's even easier to create community packages, since it doesn't rely on prototypes.  There's even https://github.com/mostjs-community 😄 

Closing since this can be provided by a community package.
