### ISSUE TITLE
Lib size

### ISSUE THREAD

**Issue by donnieflorence** [cujojs/most#351]
What is the size of most (kb)?

**Comment by davidchase** [comment]
hi @donnieflorence ,

according to [githubcdn](https://raw.githubusercontent.com/cujojs/most/master/dist/most.js) &  [cdnjs](https://cdnjs.cloudflare.com/ajax/libs/most/1.0.4/most.js) its about `22.3kb`

and minified its about `10kb`

**Comment by briancavalier** [comment]
Thanks @davidchase.

Also, most supports tree shaking builds via tools like [rollup](http://rollupjs.org).  So, you may get a smaller size if you use a tree shaking build tool to build your project.

Closing, since the question is answered, but please feel free to continue to discuss the original question.
