### ISSUE TITLE
How to import as a default

### ISSUE THREAD

**Issue by xareelee** [cujojs/most#397]
Why not supporting a default import?

```js 
import most, { of } from 'most';

console.log('most:', most);   // undefined

// OK
of(1).observe(next => console.log(next));  

// Can not use most as a default import
// raise TypeError: Cannot read property 'of' of undefined
most.of(1).observe(next => console.log(next)); 
```

**Comment by TylorS** [comment]
Hello @xareelee, thanks for your interest in most, and taking the time to open an issue. 
Currently most.js does not have a default export options for `named` exports only. This was decided before I had a chance to join the project, but I can hopefully name a few reasons what it is generally a good idea to use only named exports, and provide you with how to still achieve what you are looking for.

#### Some key reasons why defaults exports may be a bad idea.

This got longer than I planned but in short, default exports can have small quirks that lead to inconsistency and painful workarounds.

1. Using a default export can lead to inconsistent naming ( maybe trivial ). Imagine a development team of 10 or more people, and if even 1 of those people decide to change the name of the default export for any reason in something they are working on it will not be immediately obvious to any of the other developers. e.g.
  ```typescript
    // developers 1-9
    import foo from 'my-library'
    // developer 10
    import bar from 'my-library'
  ```
Again, this may be trivial, but smaller things can lead to confusion between many people with different levels of skills and knowledge. Named exports remedy this issue by always requiring users to explicitly rename an export if they wish to use different name. e.g. `import { foo as bar } from 'my-library'` thus avoiding any confusion on where a value comes from.

2. Mixing default exports and named exports lead to inconsistent builds across most (if not all) bundlers such as rollup. The mixing of default exports will lead to commonjs users to (unexpectedly) need to use `require('my-libary').default` rather than the expected `require('my-library')`. This is generally done by bundlers because if your default export is a function, and your named exports are appended to this function you will immediately take performance hits as JS engines (at least V8) will de-optimize the affected functions.

3. For those of us who use TypeScript (we do provide type defintions BTW) when there are default exports it is impossible to create type definitions that work with *both* commonjs and also ES2015 modules due to language limitations.

#### A simple alternative syntax 

In order to achieve nearly identical functionality in the presence of named exports only, you can use 
```js
import * as most from 'most'

most.of(1).observe(console.log) // 1
```
and your example will continue to work just as you'd expect.

---

Thanks again for opening this issue and I hope this has been at least slightly helpful to you. :smile:

**Comment by xareelee** [comment]
Thanks for your reply. :D
