### ISSUE TITLE
Multiple Combinators on the same stream

### ISSUE THREAD

**Issue by scorchpt** [cujojs/most#433]
### Summary
I have a multicast stream. If I create that stream using the `fromEvent` method, and try to use multiple combinators on it, it somehow only passes each value by one combinator. For example:

```javascript
const most = require("most")
const events = require("events")

const emitter = new events.EventEmitter();

const stream = most.fromEvent( 'event', emitter ).multicast()

const result = stream.take( 1 ).concat( stream.skip( 1 ) )

result.forEach( console.log.bind( console ) ); 

for ( let i = 1; i <= 5; i++ )
    emitter.emit( 'event', i );
```

I would expect the output to be `1 2 3 4 5`. Instead it is `1 3 4 5`, because since the `1` has already been processed by the `take`, when the `skip` combinator gets the first value, it is actually the `2`. However, if instead of using an EventEmitter, I used `most.from( [ 1, 2, 3, 4, 5 ] )` it works as expected.

Maybe there is something I am not seeing correctly, but I would expect both cases to behave similarly, since in both cases the listener is set up synchronously.

If this is indeed expected behaviour, what would be a solution to this problem, or rather a workaround to make it behave this way in my project?

### Versions

- most.js: 1.3.0
- node js: 6.3.1

**Comment by briancavalier** [comment]
Thanks @scorchpt.  This appears to be some sort of interaction between `multicast` and `continueWith` (the operation used to implement `concat`).  We're looking into it.

**Comment by briancavalier** [comment]
Out of curiosity, how did you arrive at this `concat(take, skip)` construct?  I'm guessing its a simplified test case of a larger use case where you saw the issue, since it's kind of an odd construct otherwise :)

Also, understanding the larger use case may help us suggest other alternatives, so that you aren't blocked by this.

Thanks!

**Comment by scorchpt** [comment]
Hi Brian. Thanks for the swift response.

I found this issue when trying to selectively map some events. Basically, I
have a stream that emits a series of events that incrementally compose the
state of the application. At one point it emit emits a single, unique ready
event signaling that the initial state is complete. After that, it emits
sporadic events changing the state of the application.

 I wanted to split the stream in two parts: before and after the ready
event. And I wanted to reduce all events before into a single, buffered
array, and emit them all as one single event. And I wanted the ones after
that to emit without change.

I know that I could do it semi-imperatively with the `loop` and a `filter`
combinator, by keeping a Boolean and a buffer as state and emit
selectively. But I wanted to try to do it declaratively.

Em 02/05/2017 12:01 da tarde, "Brian Cavalier" <notifications@github.com>
escreveu:

**Comment by briancavalier** [comment]
Thanks for the explanation, @scorchpt.  This got a bit long, but I hope it's helpful!

## Why is concat unintuitive here?

Believe it or not, why `concat` does something surprising in this case does have a somewhat logical explanation :)  It has to do with how concat works, and more specifically, _when_ it starts observing the second stream. Here's a quick explanation of what is happening:

1. Because of multicast, the take and skip are basically views / windows onto the same infinite event emitter stream.  The "take window" (that is, the *window of events* that `take` will be operating on) starts at the first event, `1`, and extends infinitely to the "right", but is then clipped after the first event by the `take(1)`.

2. However, because of the `concat`, which begins observing the second stream after the first ends, the "skip window" (the window of events that `skip` will be operating on) starts after the first event, _not because of `skip(1)`_, but rather because of concat.

    **This is the key point**:  The "subscription" to the underlying event emitter stream is delayed by `concat` until the `take(1)` stream ends, _which happens after `1`_.

3. so the events that skip is about to operate on is `2, 3, 4, 5`.  Remember: the shared underlying event emitter stream already produced `1` before `skip(1)` had a chance to see any events.

4. `skip(1)` happily skips `2`, and produces `3, 4, 5`, hence `1, 3, 4, 5`

## What to do?

Ok, given that, I think there are two options that may work for you.

### Don't skip

Perhaps most intuitively, you could remove `skip`.  For example, in your original example, this will work:

```js
const result = stream.take( 1 ).concat( stream )
```

### Merge

You could use `merge` instead of concat.

```js
const result = stream.take( 1 ).merge( stream.skip( 1 ) )
```

In fact, `merge` is a fairly appropriate operation here.  You've already guaranteed that the two streams  represent mutually exclusive parts of the timeline, so merging them would do the right thing.  Here's a quick visual example:

```
stream:  -a-b-c-d-e->
take(1): -a|
skip(1): ---b-c-d-e->
merged:  -a-b-c-d-e->
```

The reason this works is that `merge` begins observing both streams simultaneously, as opposed to `concat`, which waits until the left stream ends before observing the right.

It works for the simplified test case, but let me know if it works for your real one.

Hope that helps!

**Comment by scorchpt** [comment]
Hi @briancavalier. Thanks for the explanation. It does seem a little bit counter-intuitive, especially considering the difference between changing the source from a `most.fromEvent` to `most.from`. Although that probably stems from `most.from` re-emitting all events when a new subscriber comes in, since it has no sense of time.

I'll simply concat the streams without merging them for this project.

I have a follow-up question though. What would be the easiest and most expressive way of doing the following in most? Basically a `concat` that buffers the second stream until the first one ends, that preserves order, although does not necessarily preserve the time of the events, like so:
```
streamA:        -1-2--|
streamB:        -a--b-------c----d----e-->
A.concat( B ):  -1-2--ab---c----d----e-->
```

**Comment by briancavalier** [comment]
@scorchpt There's no existing combinator that will do that.  We'd be happy to discuss in [gitter](https://gitter.im/cujojs/most) and help you create it 😄

**Comment by briancavalier** [comment]
Hey @scorchpt.  Since you've found a solution to the original question, can we close this?

**Comment by scorchpt** [comment]
Hey, sure, sorry forgot to do that. Since it's been final's time, haven't had much time to pass by gitter to work on that combinator yet.

**Comment by briancavalier** [comment]
Thanks!
