### ISSUE TITLE
What happened to mostjs?

### ISSUE THREAD

**Issue by ElamuruganGR** [cujojs/most#555]
### Summary

What happened to mostjs?

- I don't see any new relases after sep 25 , 2017
- Is it still alive?
- Can i add mostjs for my upcoming new projects?
- Will it be maintained?

**Comment by briancavalier** [comment]
Hi @ElamuruganGR 

As mentioned at the [top of the README](https://github.com/cujojs/most#starting-a-new-project), [most/core](https://github.com/mostjs/core) is the new path for mostjs.  If you're starting a new project, we highly recommend using it.  It has [much improved documentation](https://mostcore.readthedocs.io/en/latest/), and is highly extensible via [community contributed libraries](https://github.com/mostjs-community).  There are some simple [examples here](https://github.com/mostjs/examples)

Practically speaking, the main differences you'll find with most/core, if you've used mostjs in the past will be:

1. most/core and companion libraries are function-based and not prototype method-based, so you'll mainly program with functions.
2. Projects will tend to use a few smaller, focused companion libs, instead of one monolithic mostjs.

Note that most/core is mature and stable, so will tend to be slow-changing.  Companion libs will be where new functionality is added.

I hope that helps and that you'll give most/core a try.  Cheers!
