### ISSUE TITLE
Adding to a collection during reduce, strange accumulator behavior.

### ISSUE THREAD

**Issue by nackjicholson** [cujojs/most#87]
``` 
 widgets
    .reduce(function(acc, widget) {
      acc.collection.push(widget);
      console.log(acc);
      return acc;
    }, {collection: []})
    .then(function(result) {
      console.log('I am KING NACKJICHOLSON behold my Widgets!');
    }, console.error);
```

That's what I have and the below is the console output.

```
{ collection: [ { id: 1, widgetId: 'nackjicholson-1', owner: 'nackjicholson' } ] }
{ collection: 
   [ { id: 2, widgetId: 'nackjicholson-2', owner: 'nackjicholson' },
     { id: 2, widgetId: 'nackjicholson-2', owner: 'nackjicholson' } ] }
{ collection: 
   [ { id: 3, widgetId: 'nackjicholson-3', owner: 'nackjicholson' },
     { id: 3, widgetId: 'nackjicholson-3', owner: 'nackjicholson' },
     { id: 3, widgetId: 'nackjicholson-3', owner: 'nackjicholson' } ] }
{ collection: 
   [ { id: 4, widgetId: 'nackjicholson-4', owner: 'nackjicholson' },
     { id: 4, widgetId: 'nackjicholson-4', owner: 'nackjicholson' },
     { id: 4, widgetId: 'nackjicholson-4', owner: 'nackjicholson' },
     { id: 4, widgetId: 'nackjicholson-4', owner: 'nackjicholson' } ] }
{ collection: 
   [ { id: 5, widgetId: 'nackjicholson-5', owner: 'nackjicholson' },
     { id: 5, widgetId: 'nackjicholson-5', owner: 'nackjicholson' },
     { id: 5, widgetId: 'nackjicholson-5', owner: 'nackjicholson' },
     { id: 5, widgetId: 'nackjicholson-5', owner: 'nackjicholson' },
     { id: 5, widgetId: 'nackjicholson-5', owner: 'nackjicholson' } ] }
I am KING NACKJICHOLSON behold my Widgets!
```

Is that just the intended behavior and I'm missing something? The reduce docs are a little thin. If you tell me how it works I'd be willing to make a pull to update the docs.

**Comment by briancavalier** [comment]
Hey @nackjicholson.  You'll need to show us how you are creating the `widgets` stream.  I suspect that you're reusing the same widget object, mutating it by setting it's id and widgetId over and over.  [Here's an example similar to yours](https://gist.github.com/briancavalier/50f4ab1647fccd0cc3ee) which doesn't mutate, and shows how reduce works:

In general, `stream.reduce` works exactly like `Array.prototype.reduce`, with the exception that `stream.reduce` must return a promise because streams are, by nature, asynchronous data structures.

Hope that helps.

**Comment by nackjicholson** [comment]
Thanks. I think you are right. I was using `scan` during creation of the widgets. Sorry for the non-issue, but thanks for the help!
