### ISSUE TITLE
fromDelegatedEvent

### ISSUE THREAD

**Issue by AlexGalays** [cujojs/most#97]
What's your view on supporting this?

With just "fromEvent" you can quickly have a chicken and egg problem where your view (re)renders when a stream made of data streams and input streams change, but you don't have a DOM Element reference the first time nor do you want to recreate the stream if it does change later.

With a `fromDelegatedEvent` stream, you listen at the level of a stable DOM node (some parent container) and the whole DOM hierarchy underneath it can re-render whenever the stream changes. Working with explicit DOM Element references is also not very natural when using virtual DOM libraries.

**Comment by briancavalier** [comment]
Hey @AlexGalays, good question.

It's already possible to do event delegation using `fromEvent` and `filter`, using [Element#matches](https://developer.mozilla.org/en-US/docs/Web/API/Element/matches) (and polyfills are available for older browser support).  For example:

```js
var container = document.querySelector('.some-parent-container');
most.fromEvent('click', container)
    .filter(e => e.target.matches('.some-selector'))
    .observe(e => console.log(e));
```

If you're already using another DOM library like jQuery, you can use it easily as well:

```js
var container = $('.some-parent-container');
most.create(function(add {
    container.on('click', add);
    return () => container.off('click', add);
});
```

The goal of most.js is to provide building blocks, rather than all possible functions that can be built from them.  That said, I could see a set of higher-level convenience functions, such as event delegation, being a good candidate for a companion project in another repo, like `most-dom` or something like that.

I think Node users would appreciate not having the extra DOM-related code in the most.js core as well.

Hope that helps!

**Comment by AlexGalays** [comment]
Alright cheers !
